### ISSUE TITLE
configure subdomain sprint.usds.gov

### ISSUE THREAD

**Issue by lisac-usds** [usds/discovery-sprint-guide#16]
## tasks - soft launch
- [x] create robots.txt
- [x] enable GitHub Pages
- [x] add CNAME sprint.usds.gov
- [x] verify the deployed version looks like what we expected!

## tasks - public launch
- [x] make the pages searchable (adjustments to robots.txt, noindex)
- [x] add meta tags
- [x] create sitemap.xml
- [x] make this repo public
